-- Opción A: historial real de comidas servidas por cliente/franja/semana.
-- Antes de esto no existía ningún registro de qué se sirvió en semanas
-- anteriores: plan_nutricion se sobreescribe entero en cada regeneración,
-- así que la única forma de garantizar "no repetir" (en vez de solo rotar
-- con buena probabilidad, como hace la Opción B) es guardar explícitamente
-- lo que ya se sirvió.
create table public.historial_comidas (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id),
  semana_numero int not null,
  franja text not null,
  comida_id bigint not null references public.comidas(id),
  created_at timestamptz not null default now()
);

create index historial_comidas_cliente_franja_created_idx
  on public.historial_comidas (cliente_id, franja, created_at desc);

-- Solo se escribe/lee desde rutas de servidor con el service role (igual
-- que profesionales/pagos/clientes) — RLS activo sin políticas públicas.
alter table public.historial_comidas enable row level security;
